config/routes.rb
Mediafunnel::Application.routes.draw do
  resources :users do
    collection do
      post :sign_in
      get :sign_out
    end
  end

  resources :shows do
    resources :episodes
  end
  resources :releases
  resources :subscriptions

  match 'feed/user/:id'   => 'feeds#user_feed', via: :get, as: :user_feed
  match 'feed/show/:slug' => 'feeds#show_feed', via: :get, as: :show_feed

  root 'application#landing'
end

app/models/episode.rb
class Episode
  include Mongoid::Document

  belongs_to :show
  has_many :releases, as: :releasable

  field :season, type: Integer
  field :number, type: Integer
  field :identifier

  field :title
  field :overview
  field :images, type: Hash

  field :trakt

  after_create :denormalize

  def denormalize
    self.update_attributes identifier: "#{show.title} S#{'%02d' % season}E#{'%02d' % number}"
  end
end

app/models/release.rb
class Release
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  validates_presence_of :releasable, :source, :resolution, :magnet
  validates_format_of :magnet, with: /\Amagnet:/, message: "link is not valid"

  belongs_to :releasable, polymorphic: true

  field :source # HDTV, WEB, BluRay
  field :resolution # HDTV, 720p, 1080p
  field :magnet
  field :group
end

app/models/show.rb
class Show
  include Mongoid::Document

  has_many :episodes
  has_many :subscriptions

  field :title
  field :year, type: Integer
  field :country

  field :trakt

  field :imdb_id
  field :tvdb_id
  field :tvrage_id

  field :overview
  field :runtime, type: Integer

  field :genres, type: Array
  field :images, type: Hash

  def slug
    trakt? ? trakt.split('/')[-1] : nil
  end
end

app/models/subscription.rb
class Subscription
  include Mongoid::Document

  belongs_to :user
  belongs_to :show

  field :resolution
  field :source
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  has_many :subscriptions

  field :email
  field :password
  field :username
  field :password_digest

  has_secure_password

  validates :username, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :create_guest_user, except: :landing
  before_filter :find_user

  def landing

  end

  def create_guest_user
    if session[:user_id].blank?
      @user = User.create! :username => "guest#{rand(9999)}", :email => "guest_#{Time.now.to_i}#{rand(99)}@example.com", password: "password", password_confirmation: "password"
      session[:user_id] = @user.id
    end
  end

  def find_user
    if session[:user_id]
      @user = User.find session[:user_id]
    end
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def index
    @show = Show.find_by trakt: "http://trakt.tv/show/#{ params[:show_id] }"

    respond_to do |format|
      format.json
    end
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  def user_feed
    @user = User.find params[:id]
    @releases = []

    @user.subscriptions.each do |subscription|
      subscription.show.episodes.each do |episode|
        release = episode.releases.where(resolution: subscription.resolution, source: subscription.source).order_by(created_at: :desc).first
        @releases << release if release
      end
    end

    respond_to do |format|
      format.rss { render 'feed', layout: false }
    end
  end

  def show_feed
    @show = Show.find_by trakt: "http://trakt.tv/show/#{ params[:slug] }"
    @releases = []

    @show.episodes.each do |episode|
      release = episode.releases.where(resolution: params[:resolution] || '480p', source: params[:source] || 'HDTV').order_by(created_at: :desc).first
      @releases << release if release
    end

    respond_to do |format|
      format.rss { render 'feed', layout: false }
    end
  end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  before_filter :create_guest_user
  def index
    @release = Release.new
    @releases = Release.order_by(created_at: :desc)

    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end

  def create
    @release = Release.new release_params

    if @release.valid?
      @release.save
      redirect_to action: :index
    else
      @releases = Release.order_by(created_at: :desc)
      render 'index'
    end
  end

private

  def release_params
    params.require(:release).permit(:source, :resolution, :releasable_id, :releasable_type, :group, :magnet)
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_filter :create_guest_user

  def index
    @shows = Release.where(releasable_type: 'Episode').map(&:releasable).map(&:show).uniq
    if params[:genre].present?
      @shows = @shows.select { |show| show.genres.include? params[:genre] }
    end

    @genres = []

    Show.each do |show|
      @genres |= show.genres
    end

    @genres = @genres.sort
    @genres[0] = ['All', '']
  end

  def show
    @show = Show.find_by trakt: "http://trakt.tv/show/#{ params[:id] }"
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    @subscriptions = @user.subscriptions.includes(:show)

    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end

  def create
    subscription = Subscription.new subscription_params
    subscription.user = @user
    subscription.upsert
    redirect_to show_path(subscription.show.slug)
  end

  def destroy
    subscription = Subscription.find params[:id]
    redirect_to show_path(subscription.show.slug)
    subscription.destroy
  end

private

  def subscription_params
    params.require(:subscription).permit(:show_id, :source, :resolution)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :create_guest_user, only: :sign_in
  skip_before_filter :find_user,         only: :sign_in

  def sign_in
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id

      flash[:notice] = "You have successfully logged in."
      redirect_to releases_path
    else
      flash[:alert] = "Those credentials were incorrect."
      redirect_to root_path
    end
  end

  def sign_out
    session[:user_id] = nil
    flash[:notice] = "You have been logged out"
    redirect_to root_path
  end

  def edit

  end

  def update
    if @user.update_attributes(user_params)
      redirect_to '/shows', flash: { success: 'Client user was successfully updated.' }
    else
      render :edit
    end
  end

  def user_params
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end
    params[:user].permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/landing.html.erb
<div class="banner">
  <div class="container">
    <h1>
      <%= image_tag 'icon-video-cam.svg' %>
      Find media
    </h1>
    <h2>...all in one place</h2>
  </div>
</div>

<div class="container">
    <div class="feature aggregate">
      <h2><i class="icon-globe"></i>Aggregate</h2>
      <p>
        Collect and share links for media from all over the web. Nothing is stored in Mediafunnel, it leverages the infrastructure already in place elsewhere.
      </p>
    </div>

    <div class="feature filter">
      <h2><i class="icon-filter"></i>Filter</h2>
      <p>
        Specify your preferences of quality, source and more and we'll automatically filter out the links that don't match.
      </p>
    </div>

    <div class="feature subscribe">
      <h2><i class="icon-rss"></i>Subscribe</h2>
      <p>
        Are you tired of constantly checking sites for content? So are we! Simply set up some subscriptions and hook up to your personalized RSS feed to leave yet another repetitive task to a computer somewhere.
      </p>
    </div>

    <div class="feature guest-access">
      <h2><i class="icon-group"></i>Guest Access</h2>
      <p>
        Don't want another login to remember? No problem. Just add some subscriptions and use the RSS feed provided. As long as you keep checking the feed we will keep your settings without you having to sign up.
      </p>
    </div>
</div> <!-- end application-content -->

app/views/layouts/_nav.html.erb
<nav id="menu">
  <ul class="menu menu-bar">
    <span class="logo"><a href="/"><span>MediaFunnel</span></a></span>
    <li ><%= link_to 'Home', root_path %></li>
    <li ><%= link_to 'Releases', releases_path %></li>
    <li ><%= link_to 'Subscriptions', subscriptions_path %></li>
    <li ><%= link_to 'Shows', shows_path %></li>

    <%- if @user -%>
      <li class="pull-right"><%= link_to 'Logout', sign_out_users_path %></li>
      <li class="pull-right"><%= link_to @user.username, edit_user_path(@user) %></li>
    <%- else -%>
      <li class="login-form pull-right">
        <%= form_for User.new, url: sign_in_users_path, html: { :class => 'pure-form' }  do |f| %>
          <%= f.text_field :email, placeholder: "Email" %>
          <%= f.password_field :password, placeholder: "Password" %>
          <%= f.submit 'Sign In', :class=> 'button sign-in' %>
        <% end %>
      </li>
    <%- end -%>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediaFunnel</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Raleway:200,400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render partial: 'layouts/nav' %>
  </div>
  <div class="color-line-header"></div>

  <%= yield %>

  <div class="container">
    <div class="footer">
      <p>made possible by <a href="http://trakt.tv">Trakt</a> and <a href="http://www.platform45.com">Platform45</a></p>
    </div>
  </div>
 <div class="color-line-footer"></div>
</body>
</html>

app/views/releases/index.html.erb
<div id="releases">
  <div class="page-banner">
    <div class="container">
      <h1><i class="icon-circle-arrow-right"></i> Latest Releases</h1>
    </div>
  </div>

  <div class="container">
    <%= form_for @release, html: { class: 'add-release-form' } do |f| %>
      <%= f.hidden_field :releasable_type, value: 'Episode' %>
      <fieldset>
        <legend>Add a Release</legend>
        <% if @release.errors.any? %>
          <div class="errors">
            <%= @release.errors.full_messages.to_sentence %>
          </div>
        <% end %>

        <div class="left-align-container">
          <div class="show-box">
            <%= label_tag :show_slug, "Show" %><br>
            <%= select_tag :show_slug, options_from_collection_for_select(Show.order_by(title: :asc), :slug, :title), prompt: "Select a show", required: true, onchange: 'window.getEpisodes()' %>
          </div>

          <div class="episode-select">
            <%= f.label :releasable_id, "Episode" %><br>
            <%= f.select :releasable_id, [], prompt: "First select a show...", required: true %>
          </div>

          <div class="inputs">
            <%= f.label :resolution %><br>
            <%= f.select :resolution, ['480p', '720p', '1080p'] %>
          </div>

          <div class="inputs">
            <%= f.label :source %><br>
            <%= f.select :source, ['HDTV', 'WEB-DL', 'BluRay'] %>
          </div>

          <div class="inputs">
            <%= f.label :group %><br>
            <%= f.text_field :group %>
          </div>

          <div class="magnet-link">
            <%= f.label :magnet, 'Magnet Link' %>
            <%= f.text_area :magnet, cols: '80', rows: '4', required: true %>
          </div>

          <div class="submit-button">
            <button type="submit" class="button">Create</button>
          </div>
        </div>
      </fieldset>
    <% end %>

    <fieldset>
      <legend>List to Download</legend>
      <table class="release-table">
        <thead><tr>
          <th>Title</th>
          <th>Details</th>
          <th>Download</th>
          <th>Added</th>
        </tr></thead>
        <tbody>
          <%- @releases.each do |release| -%>
          <tr class="release">
            <td><%= link_to release.releasable.identifier, show_path(release.releasable.show.slug) if release.releasable %></td>
            <td>
              <span class="resolution"><%= release.resolution %></span>
              <span class="source"><%= release.source %></span>
              <span class="group"><%= release.group %></span>
            </td>
            <td><i class="icon-magnet"></i> <%= link_to 'Magnet', release.magnet %></td>
            <td><%= time_ago_in_words release.created_at %> ago</td>
          </tr>
          <%- end -%>
        </tbody>
      </table>
    </fieldset>
  </div>
</div>

app/views/shows/index.html.erb
<div id="shows">
  <div class="page-banner">
    <div class="container">
      <h1><i class="icon-circle-arrow-right"></i> Shows</h1>
    </div>
  </div>

  <div class="container">
    <form class="filter">
        <label>Filter by Genre:</label>
        <%= select_tag :show_genre, options_for_select(@genres.collect, selected: params[:genre]), onchange: 'window.filterShows()' %>
    </form>
  </div>

  <div class="container">
    <%- @shows.each do |show| -%>
    <div class="grid-show">
      <div class="poster">
        <img src="<%= show.images['poster'] %>" />
      </div>
      <div class="details">
        <h4><%= link_to show.title, show_path(show.slug) %></h4>
      </div>
    </div>
    <%- end -%>
  </div>
</div>

app/views/shows/show.html.erb
<div class="container" id="shows">
  <%= image_tag @show.images['banner'], width: '100%'%>
  <%- if @show.images['banner'] == 'http://slurm.trakt.us/images/banner.jpg' -%>
  <span class="show-title"><%= @show.title %></span>
  <%- end -%>

  <%- if @user.subscriptions.any? { |sub| sub.show == @show } -%>
    <%- subscription = @user.subscriptions.find_by(show_id: @show._id) -%>
    <p>
      You subscribe to this show in <%= subscription.resolution %> <%= subscription.source %>.
      <%= link_to 'Unsubscribe', subscription_path(subscription), method: :delete %>
    </p>
  <%- else -%>
    <%= form_for Subscription.new(show: @show) do |f| %>
      <%= f.hidden_field :show_id, value: @show._id %>
      <div class="left-align-container show">
        <div class="inputs source">
          <%= f.label :source %>
          <%= f.select :source, ['HDTV', 'WEB-DL', 'BluRay'] %>
        </div>

        <div class="inputs">
          <%= f.label :resolution %>
          <%= f.select :resolution, ['480p', '720p', '1080p'] %>
        </div>

        <div class="inputs">
          <%= f.submit 'Add to subscriptions', class: 'button subscribe' %>
        </div>
      </div>
    <% end %>
  <%- end -%>
  <p>
    <%= link_to show_feed_path(@show.slug, format: :rss, resolution: '720p', source: 'WEB-DL'), class: 'rss' do %>
      <i class="icon-rss"></i> 720p WEB-DL
    <% end %>

    <%= link_to show_feed_path(@show.slug, format: :rss), class: 'rss' do %>
      <i class="icon-rss"></i> 480p HDTV
    <% end %>
  </p>

  <p><%= link_to 'View on Trakt', @show.trakt if @show.trakt? %></p>
  <p class="genres">Genres: <%= @show.genres.join ', ' %></p>
  <p><%= @show.overview %></p>

  <fieldset><legend>Episodes</legend>

    <table class="pure-table pure-table-horizontal pure-table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Title</th>
        </tr>
      </thead>
    <%- @show.episodes.each do |episode| -%>
      <tr>
        <td><%= '%02d' % episode.season %>x<%= '%02d' % episode.number %></td>
        <td><%= episode.title %></td>
      </tr>
    <%- end -%>
    </table>
  </fieldset>
</div>

app/views/subscriptions/index.html.erb
<div id="subscriptions">
  <div class="page-banner">
    <div class="container">
      <h1><i class="icon-circle-arrow-right"></i> Your Subscriptions</h1>
    </div>
  </div>

  <div class="container">
    <fieldset>
      <legend>
        Your Personalized Feed
        <%= link_to user_feed_url(@user._id, format: :rss), class: 'rss' do %>
          <i class="icon-rss"></i> Subscribe
        <% end %>
      </legend>

      <table>
        <thead>
          <tr>
            <th>Show</th>
            <th>Conditions</th>
            <th></th>
          </tr>
        </thead>
      <%- @subscriptions.each do |subscription| -%>
        <tr>
          <td><%= link_to subscription.show.title, show_path(subscription.show.slug) %></td>
          <td>
            <span class="tag"><%= subscription.resolution %></span>
            <span class="tag"><%= subscription.source %></span>
          </td>
          <td><%= link_to 'Unsubscribe', subscription_path(subscription), method: :delete %></td>
        </tr>
      <%- end -%>
      </table>
    </fieldset>
  </div>
</div>

app/views/users/_form.html.erb
<div class="left-align-container">
  <%= form_for @user, html: { class: 'user-form' } do |f| %>
    <fieldset>
      <legend>Update Profile</legend>
      <div class="form-elements">
        <%= f.label :username, "Username" %>
        <%= f.text_field :username,required: true %>
      </div>

      <div class="form-elements">
        <%= f.label :email, "Email" %>
        <%= f.text_field :email,required: true %>
      </div>
      <div class="form-elements">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password %>
      </div>
      <div class="form-elements">
        <%= f.label :password_confirmation, "Password Confirmation" %>
        <%= f.password_field :password_confirmation %>
      </div>

       <div class="submit-button">
        <button type="submit" class="button button-big">Update Profile</button>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <%= render partial: 'form' %>
</div>